FROM hashicorp/packer:latest

# Installation des dépendances et d'Ansible via apk
RUN apk add --no-cache \
    python3 \
    py3-pip \
    openssh-client \
    py3-ansible \
    ansible

# Vérification des installations
RUN packer --version && ansible --version