steps:
  # Construction de l'image avec Packer et Ansible
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/${PROJECT_ID}/packer-ansible',
      '-f', '/workspace/ops/packer/Dockerfile',
      '.'
    ]

  # Initialisation de Packer
  - name: 'gcr.io/${PROJECT_ID}/packer-ansible'
    entrypoint: 'packer'
    args: ['init', '/workspace/ops/packer/build.pkr.hcl']
    
  # Build de l'image
  - name: 'gcr.io/${PROJECT_ID}/packer-ansible'
    entrypoint: 'packer'
    args: [
      'build',
      '-var', 'project_id=${PROJECT_ID}',
      '/workspace/ops/packer/build.pkr.hcl'
    ]

images:
  - 'gcr.io/${PROJECT_ID}/packer-ansible'

timeout: "1800s"