steps:
  # Vérification de la structure
  - name: 'ubuntu'
    args: ['ls', '-R', '/workspace']

  # Construction de l'image avec Packer et Ansible
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'packer-ansible',
      '-f', '/workspace/ops/packer/Dockerfile',
      '.'
    ]

  # Initialisation de Packer
  - name: 'packer-ansible'
    args: ['init', '/workspace/ops/packer/build.pkr.hcl']
    
  # Build de l'image
  - name: 'packer-ansible'
    args: [
      'build',
      '-var', 'project_id=${PROJECT_ID}',
      '/workspace/ops/packer/build.pkr.hcl'
    ]

timeout: "1800s"