---
- name: Configure application server
  hosts: all
  become: yes
  
  tasks:
    - name: Create required directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items:
        - /opt/app
        - /tmp/app

    # Téléchargement avec debug
    - name: Download application from Artifact Registry
      shell: |
        gcloud artifacts files download cesiappgo:1.0:app.tar.gz/app.tar.gz \
          --project={{ project_id | default('cesi-ops') }} \
          --location=europe-west9 \
          --repository=app-repo \
          --destination=/tmp/app
      register: download_result

    # Ajout de commandes de debug
    - name: Debug - Show download result
      debug:
        var: download_result

    - name: Debug - List tmp directory
      shell: "ls -R /tmp/app"
      register: ls_result

    - name: Show directory content
      debug:
        var: ls_result.stdout_lines

    - name: Find tar.gz file
      shell: "find /tmp/app -name '*.tar.gz'"
      register: find_result

    - name: Show found files
      debug:
        var: find_result.stdout_lines

    - name: Extract application
      unarchive:
        src: "{{ find_result.stdout_lines[0] }}"  # Utilise le premier fichier trouvé
        dest: /opt/app
        remote_src: yes

    - name: Set permissions
      file:
        path: /opt/app
        state: directory
        recurse: yes
        mode: '0755'

    - name: Create systemd service
      template:
        src: app.service.j2
        dest: /etc/systemd/system/app.service
        mode: '0644'
      notify: restart app

  handlers:
    - name: restart app
      systemd:
        name: app
        state: restarted
        daemon_reload: yes

  roles:
    - ops_agent